#!/usr/bin/env expect

# disables script output
log_user 0

spawn tmux

# Waiting for tmux to attach. If this is not done, next command, `send` will
# not work properly.
sleep 1

# this is tmux prefix + I
send "I"

# cloning might take a while
set timeout 15

expect {
  "Installing \"tmux-example-plugin\"" {

    expect {
      "\"tmux-example-plugin\" download success" {

        expect { "Done, press ENTER to continue" { exit } }

      }
    }

  }

  timeout {
    puts "Plugin update timeout";
    exit 1
  }
}
