#!/usr/bin/env bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPTS_DIR="$CURRENT_DIR/../scripts"

source "$SCRIPTS_DIR/shared_functions.sh"

main() {
	reload_tmux_environment
	"$SCRIPTS_DIR/install_plugins.sh" --tmux-echo >/dev/null 2>&1
	reload_tmux_environment
	end_message
}
main
